2021-06-01 10:4716 DEBUG Logger Initialized
2021-06-01 10:5219 DEBUG Logger Initialized
2021-06-01 10:5829 DEBUG Logger Initialized
2021-06-01 11:0636 DEBUG Logger Initialized
2021-06-01 11:1621 DEBUG Logger Initialized
2021-06-01 16:4718 DEBUG Logger Initialized
2021-06-01 16:4748 DEBUG Logger Initialized
2021-06-01 16:4915 DEBUG Logger Initialized
2021-06-01 17:0429 DEBUG Logger Initialized
2021-06-01 17:1543 DEBUG Logger Initialized
2021-06-01 17:2229 DEBUG Logger Initialized
2021-06-01 17:3046 ERROR __ERROR__ ->'MongoConn' object has no attribute 'client'
Traceback (most recent call last):
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/ImageMatchingServices/main_image_matching_service.py", line 57, in image_matching_main_service_method
    mongo_conn_obj = MongoConn(server=server)
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/MongoConnection/mongo_connection.py", line 19, in __init__
    self.db = self.client[utils.configuration["mongodb_credentials"][server]["database_testing"]]
AttributeError: 'MongoConn' object has no attribute 'client'
2021-06-01 17:3126 ERROR __ERROR__ ->'MongoConn' object has no attribute 'client'
Traceback (most recent call last):
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/ImageMatchingServices/main_image_matching_service.py", line 57, in image_matching_main_service_method
    mongo_conn_obj = MongoConn(server=server)
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/MongoConnection/mongo_connection.py", line 19, in __init__
    self.db = self.client[utils.configuration["mongodb_credentials"][server]["database_testing"]]
AttributeError: 'MongoConn' object has no attribute 'client'
2021-06-01 17:3149 ERROR __ERROR__ ->'MongoConn' object has no attribute 'client'
Traceback (most recent call last):
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/ImageMatchingServices/main_image_matching_service.py", line 57, in image_matching_main_service_method
    mongo_conn_obj = MongoConn(server=server)
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/MongoConnection/mongo_connection.py", line 19, in __init__
    self.db = self.client[utils.configuration["mongodb_credentials"][server]["database_testing"]]
AttributeError: 'MongoConn' object has no attribute 'client'
2021-06-01 17:3329 DEBUG Logger Initialized
2021-06-01 17:3446 ERROR __ERROR__ ->'MongoConn' object has no attribute 'client'
Traceback (most recent call last):
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/ImageMatchingServices/main_image_matching_service.py", line 57, in image_matching_main_service_method
    mongo_conn_obj = MongoConn(server=server)
  File "/home/amitparashar/afghaniFolder/LinkCXO_work/MyNewExperiment_xfactor_3.x/ImageMatching/xfactor_image_match_microservices_v3.2.3/Scripts/Services/MongoConnection/mongo_connection.py", line 19, in __init__
    self.db = self.client[utils.configuration["mongodb_credentials"][server]["database"]]
AttributeError: 'MongoConn' object has no attribute 'client'
2021-06-01 17:3824 DEBUG Logger Initialized
2021-06-01 19:0200 DEBUG Logger Initialized
2021-06-01 19:0448 DEBUG Logger Initialized
2021-06-01 19:0455 ERROR Exception occurred'testing_server'
2021-06-01 19:0532 DEBUG Logger Initialized
2021-06-01 22:0327 DEBUG Logger Initialized
2021-06-01 22:1546 DEBUG Logger Initialized
2021-06-01 22:2158 DEBUG Logger Initialized
2021-06-01 22:3045 DEBUG Logger Initialized
2021-06-01 22:3341 DEBUG Logger Initialized
2021-06-01 22:3618 DEBUG Logger Initialized
2021-06-01 22:3625 DEBUG Logger Initialized
